apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: test-pvc-home
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: standard
   volumeMode: Filesystem
   resources:
       requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: test-pvc-srv
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: standard
   volumeMode: Filesystem
   resources:
       requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: test-pvc-etc
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: standard
   volumeMode: Filesystem
   resources:
       requests:
          storage: 1Gi